### ISSUE TITLE
Implement DepthOfFieldEffect

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#569]
### Description

Implement a `DepthOfFieldEffect` based on the [implementation in v6](https://github.com/pmndrs/postprocessing/blob/e053ac37ed095fafa31d3bb377e37ffa7810f12b/src/effects/DepthOfFieldEffect.js).

### Tasks

- [ ] Create CoC shader.
- [ ] Create blur shader.
- [ ] Create `DepthOfFieldEffect`.
- [ ] Create `depth-of-field` demo (manual).
- [ ] Add unit test.

### Implementation Details

- The CoC should be calculated based on fragment distance instead of depth.
- Consider using a more general name for the disc blur shader.
- Add support for logarithmic depth.

**Comment by hichemfantar** [comment]
what's the difference this and the v6 implementation?

**Comment by vanruesc** [comment]
Support for log depth and inversed depth, better configuration options and more natural circle of confusion based on distance instead of linear depth. There may also be some other aspects that can be improved based on the linked article.
