### ISSUE TITLE
Add support for scissor and viewport settings

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#570]
### Description

Add support for scissor/viewport settings to `Pass` and `RenderPipeline`.

Related: #386

### Tasks

- [ ] Add `scissor` and `viewport` settings to `Pass`.
- [ ] Consider also adding `scissor` and `viewport` settings to `RenderPipeline`.
- [ ] Check if such settings also make sense elsewhere.
- [ ] Add a `scissor-viewport` demo.

### Implementation Details

- Use the [scissor](https://threejs.org/docs/?q=webglr#api/en/renderers/WebGLRenderTarget.scissor), [scissorTest](https://threejs.org/docs/?q=webglr#api/en/renderers/WebGLRenderTarget.scissorTest) and [viewport](https://threejs.org/docs/?q=webglr#api/en/renderers/WebGLRenderTarget.viewport) settings on `WebGLRenderTarget`.

**Comment by vanruesc** [comment]
@jo-chemla scissor/viewport settings have landed in [v7.0.0-beta.5](https://github.com/pmndrs/postprocessing/releases/tag/v7.0.0-beta.5).

Pass now has `viewport` and `scissor` properties and `RenderPipeline` can set the viewport/scissor for all passes via `setViewport` and `setScissor`. Here's an example of how to use it: https://github.com/pmndrs/postprocessing/blob/dfe16f129664480ae75ac5bbc2dcfc80146f8269/manual/assets/js/src/demos/scissor-viewport.ts#L102

**Comment by drone1** [comment]
amazing, tysm!

btw, any performance concerns that you're aware of?

**Comment by vanruesc** [comment]
> btw, any performance concerns that you're aware of?

None that I'm aware of 👍
