### ISSUE TITLE
Implement LUT3DEffect

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#575]
### Description

Implement a `LUT3DEffect` based on the [implementation in v6](https://github.com/pmndrs/postprocessing/blob/e053ac37ed095fafa31d3bb377e37ffa7810f12b/src/effects/LUT3DEffect.js).

References:
- https://affinityspotlight.com/article/1d-vs-3d-luts/

### Tasks

- [x] Create `LUT3DEffect`.
- [x] Create `lut` demo.
- [x] Add unit test.

### Implementation Details

- The implementation requires minimal adjustments.
- WebGL 2 is now required which means that 3D textures can be assumed to be available.
  - Support for 2D LUTs should be removed.
  - `LookupTexture` must be updated accordingly.
