### ISSUE TITLE
Implement OutlineEffect

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#583]
### Description

Implement an `OutlineEffect`.

Related: #320, #352

### Tasks

- [ ] Use `EdgeDetectionMaterial` or implement `SobelMaterial`.
- [ ] Create `OutlineEffect`.
- [ ] Create `outline` demo.
- [ ] Add unit test.

### Implementation Details

- Should be done after `GBuffer.ID` is implemented.
- Use G-Buffer component (object ID) to control which objects should be outlined.
  - Implement `Selective` and use selection to control ID mask.
- Support per-object settings (suggestions):
  - Provide method to set settings for specific objects and store the data in a texture.
  - Object data can be fetched via object ID (downside: potentially slow, dependent texel fetch).
- Mask ID texture > detect outlines > blur if needed > mask again to remove inward blur > blend on top.
- Use smoothstep to control cutoff and softness of outlines.
- Overlay texture feature from previous `OutlineEffect` should not be included.
