### ISSUE TITLE
Auto resource optimizations

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#633]
### Description

Implement automatic resource optimizations for render targets.

### Tasks

- [ ] Manage `WebGLRenderTarget` and `Texture` instances via `Resource` wrappers.
- [ ] Implement reactive, event-based I/O.
- [ ] Analyze passes and effects on I/O changes to deduplicate render targets and textures.
- [ ] Make sure this doesn't break anything by adding tests :boom:
